# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml 참고
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck

  nonamedreturns:
    report-error-in-defer: true

linters-settings:
  errcheck:
    check-defer: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
