name: my-ci

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          directory: "./"

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Apply Prettier formatting"

  go-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.4"

      - name: Display Go version
        run: go version

  go-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go environment
        run: |
          export PATH=$PATH:/usr/local/go/bin
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          export GOROOT=/usr/lib/go-1.13
          export PATH=$PATH:$GOROOT/bin

      - name: Download dependencies
        run: go mod download
